### ISSUE TITLE
Fatal Exception: java.lang.StackOverflowError: stack size 1039KB

### ISSUE THREAD

**Issue by farhan-spinny** [microsoft/clarity-apps#5]
Getting this crash after adding clarity. 
version
react-native-clarity 0.0.3

`Fatal Exception: java.lang.StackOverflowError: stack size 1039KB
       at org.glassfish.json.JsonPatchImpl$DiffGenerator.emit(JsonPatchImpl.java:312)
       at org.glassfish.json.JsonPatchImpl$DiffGenerator.emit(JsonPatchImpl.java:312)
       at org.glassfish.json.JsonPatchImpl$DiffGenerator.emit(JsonPatchImpl.java:312)
       at org.glassfish.json.JsonPatchImpl$DiffGenerator.emit(JsonPatchImpl.java:312)
       at org.glassfish.json.JsonPatchImpl$DiffGenerator.lambda$diffObject$0$org-glassfish-json-JsonPatchImpl$DiffGenerator(JsonPatchImpl.java:251)
       at org.glassfish.json.JsonPatchImpl$DiffGenerator$$ExternalSyntheticLambda0.accept(:10)
       at java.util.Map.forEach(Map.java:659)
       at org.glassfish.json.JsonPatchImpl$DiffGenerator.diffObject(JsonPatchImpl.java:249)
       at org.glassfish.json.JsonPatchImpl$DiffGenerator.diff(JsonPatchImpl.java:240)
       at org.glassfish.json.JsonPatchImpl$DiffGenerator.diff(JsonPatchImpl.java:229)
       at org.glassfish.json.JsonPatchImpl.diff(JsonPatchImpl.java:154)
       at org.glassfish.json.JsonProviderImpl.createDiff(JsonProviderImpl.java:238)
       at javax.json.Json.createDiff(Json.java:399)
       at com.microsoft.clarity.models.ingest.mutation.MutationEvent$Companion.getMutationPayload(:17)
       at com.microsoft.clarity.models.ingest.mutation.MutationEvent$Companion.make(:5)
       at a.a.a.s.f.a(:38)
       at a.a.a.s.b$a.a(:5)
       at a.a.a.s.a$f.invoke(:15)
       at a.a.a.y.b$a.a(:5)
       at a.a.a.y.b$a.a(:11)
       at a.a.a.s.a.a(:36)
       at a.a.a.s.a$$ExternalSyntheticLambda0.run(:2)
       at java.lang.Thread.run(Thread.java:1012)
       `

Any suggestions?

**Comment by ibradwan** [comment]
Hello Farhan,

Thank you for reporting this. We currently have a fix for this issue and it should be released soon. Could you also please provide us with your project id/application package name (through clarity-apps-support@microsoft.com)? This should help us make sure that the fix when applied to your application would solve this problem. Thank you.

**Comment by himanshukansal27** [comment]
@ibradwan any update on the same? Any ETA for the issue resolution?

**Comment by riteshshukla04** [comment]
++ 
We are facing the same issue

**Comment by nouranmaher86** [comment]
Hello - 
We have released Clarity SDK version 0.0.4 for React Native - Can you try upgrading your SDK and see if this error is resolved?

**Comment by mununki** [comment]
The issue seems not resolved. I still have same error after upgrading 0.0.4 for React Native.

**Comment by Sun-Woo-Kim** [comment]
Same issue  v0.0.4 for React Native.

**Comment by nouranmaher86** [comment]
Hello - This is Nouran from MS Clarity Mobile SDK team. We are working on a fix to remove dependencies that will be released by end of June. Stay Tuned!

**Comment by nouranmaher86** [comment]
The new version of Clarity SDK has been released today. This version should resolve this error and address a lot of the dependency issues. Can you please upgrade and let us know your feedback?
