### ISSUE TITLE
[BUG][Android] Clarity Library causing OOM exceptions on Android

### ISSUE THREAD

**Issue by Davaeth** [microsoft/clarity-apps#76]
**Describe the Bug**
We are getting Out Of Memory exceptions while users interacts with our product listing and product items. It started appearing right away when we added clarity library to app. We were forced to remove library from app for now.

**Repro Steps**
we were not able to reproduce it ourselves, but our Crashlytics reports shown fast peaking OOM exceptions.

**Expected Behavior**
Adding clarity library does not cause any exceptions.

**Screenshots**
![Image](https://github.com/user-attachments/assets/ed4a3f6b-8b8c-4767-a9b2-a7a512b62922)

**Project Info**
E-commerce application

**Platform/Framework Info**

- Device: mostly Samsung Galaxy, but various devices like Pixel, Xiaomi, Poco, etc.
- OS: Android, versions 12-14
- Application Framework Android
- Clarity Version 2.5.2

**Comment by ibradwan** [comment]
Hi @Davaeth,

Thanks for reporting this issue. Could u please share the full stack trace of the issue? Also, what's the frequency of the crashes? Finally, is your project imagery-heavy or uses large custom fonts?

**Comment by ibradwan** [comment]
Is this the same stack trace for all crashes? Would u also please send your project id to clarity-apps-support@microsoft.com?

**Comment by m-szczepanowski** [comment]
The stack trace isnt the same for each variant, and we have quite a few of those. 
I have sent the project id on the email provided.

**Comment by panMayur** [comment]
We're also facing the OOM after adding clarity to the application. Issues are not replicable and happen many times, thinking clarity is doing more memory consumption tasks which led to OOM exception.

Device info:
Model: Faced on Moto G53 5G, Galaxy A05, Galaxy A23 and many
Android version: 14, 13
Clarity version: 2.5.2
Every device has almost 1GB of free RAM

stack traces:
```
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 84328 byte allocation with 136864 free bytes and 133KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.

java.util.Arrays.copyOf (Arrays.java:3560)
java.util.Arrays.copyOf (Arrays.java:3529)
java.util.ArrayList.grow (ArrayList.java:244)
java.util.ArrayList.grow (ArrayList.java:251)
java.util.ArrayList.add (ArrayList.java:490)
java.util.ArrayList.add (ArrayList.java:503)
com.microsoft.clarity.e.o.a (SourceFile:48)
com.microsoft.clarity.f.e.invoke (SourceFile:10)
com.microsoft.clarity.n.k.a (Unknown Source:22)
com.microsoft.clarity.f.f$a.invoke (SourceFile:7)
com.microsoft.clarity.n.d.a (Unknown Source:5)
com.microsoft.clarity.n.d.a (Unknown Source:12)
com.microsoft.clarity.f.f.a (Unknown Source:32)
com.microsoft.clarity.f.f$$ExternalSyntheticLambda0.run (D8$$SyntheticClass)
java.lang.Thread.run (Thread.java:1012)
```

other crash:
```
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 1385928 byte allocation with 105896 free bytes and 103KB until OOM, target footprint 268435456, growth limit 268435456

java.util.Arrays.copyOf (Arrays.java:3585)
java.lang.AbstractStringBuilder.ensureCapacityInternal (AbstractStringBuilder.java:177)
java.lang.AbstractStringBuilder.append (AbstractStringBuilder.java:543)
java.lang.StringBuilder.append (StringBuilder.java:186)
com.microsoft.clarity.models.ingest.mutation.MutationEvent.serialize (Unknown Source:57)
com.microsoft.clarity.k.e.a (Unknown Source:12)
com.microsoft.clarity.f.r$f.invoke (SourceFile:18)
com.microsoft.clarity.f.r$a.invoke (SourceFile:5)
com.microsoft.clarity.n.d.a (Unknown Source:5)
com.microsoft.clarity.n.d.a (Unknown Source:12)
com.microsoft.clarity.f.r.a (Unknown Source:18)
com.microsoft.clarity.f.r$$ExternalSyntheticLambda0.run (D8$$SyntheticClass)
java.lang.Thread.run (Thread.java:1012)
```

**Comment by abhishek4133** [comment]
Facing the similar issue in our end as well, even on android 12 devices we are getting similar crash.

**Comment by ibradwan** [comment]
Hey,

Thank you all for sharing the valuable feedback. We're working on a major optimization that should reduce our memory footprint, please stay tuned for an update.

**Comment by android-dev-cpu** [comment]
We have tens of hundreds of daily OOM crashes due to clarity sdk. The OOMs happen because we add and remove views from our view hierarchy but clarity adds the views as ondrawlisteners to the main viewtreeobserver and leaks them there. When we remove the views from our view hierarchy they are actually leaked in the windows main view tree observer. Clarity does not remove them from there. Can you please verify this happens.

**Comment by ibradwan** [comment]
@android-dev-cpu Thanks for the detailed feedback, will confirm and get back to you.

**Comment by ibradwan** [comment]
@android-dev-cpu After running some tests, turns out you're right to some extent. We've a condition in place that would prevent this problem, but the by time it activates, it might be too late especially if you're doing many view hierarchy manipulations. Anyway, we had a fix for this in the pipeline to be released with our next release, but since it's affecting you, we'll make sure to release a hotfix asap.

**Comment by android-dev-cpu** [comment]
Thank you very much for the quick reaction. We are really happy to hear that. We are able to reproduce it locally very easy - we add a view and wait for about 10 seconds then remove it from the view hierarchy. We repeat these steps a few times - as our views hold bitmaps they easily grow and cause OOM crashes. Even if we clear the bitmaps a lot of references are still held and leaked through these views. After some investigation we found that they are held in the onDrawLisnters array in the activity's ViewTreeObserver and never cleared.

**Comment by ibradwan** [comment]
@android-dev-cpu since it's easily reporable locally on your side, could u please try version 3.1.3 and see if it solves the problem for you?

**Comment by android-dev-cpu** [comment]
@ibradwan - We can confirm the issue is fixed. Thank you very much! We will release with 3.1.3

**Comment by saurabhspinny** [comment]
> [@ibradwan](https://github.com/ibradwan) - We can confirm the issue is fixed. Thank you very much! We will release with 3.1.3

@android-dev-cpu I am trying to use this version with react native. But it seems like it does not exist for react native.

**Comment by ibradwan** [comment]
@saurabhspinny React Native versions are different than the native one, you can install the latest version using:
`npm install @microsoft/react-native-clarity`. The latest version includes the fixes as well.

**Comment by saurabhsaneja** [comment]
@ibradwan i installed react-native-clarity 4.1.4. In its build.gradle file within dependencies section, i can see clarity version is 3.1.3

**Comment by ibradwan** [comment]
Yes, because our React Native package is just a wrapper around our native ones. Now you should have the latest fixes with regards to the beforementioned issue.

**Comment by Allen-ZXJ** [comment]
> [@android-dev-cpu](https://github.com/android-dev-cpu) since it's easily reporable locally on your side, could u please try version 3.1.3 and see if it solves the problem for you?

I run the version 3.1.3 with the Android Profiler，but in fact this byte[] data is still very large, I captured the stack byte[] data peak 360MB+, and when I repeatedly scroll and refresh the list of items, OOM anomaly appeared.
` FATAL EXCEPTION: OkHttp Dispatcher
                                                                                                    Process: com.xxx, PID: 12596
                                                                                                    java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 1084680 free bytes and 1059KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
                                                                                                    	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
                                                                                                    	at java.lang.Thread.getStackTrace(Thread.java:1841)
                                                                                                    	at com.cider.utils.LogUtil.getCallerStackTraceElement(LogUtil.java:246)
                                                                                                    	at com.cider.utils.LogUtil.i(LogUtil.java:126)
                                                                                                    	at com.cider.network.RetrofitHelper.getRequestBodyMap(RetrofitHelper.java:624)
                                                                                                    	at com.cider.network.RetrofitHelper$2.getSecretStrMap(RetrofitHelper.java:500)
                                                                                                    	at com.cider.network.RetrofitHelper$2.intercept(RetrofitHelper.java:362)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2025-02-10 10:49:41.529 12596-23777 AndroidRuntime          com.cider.debug                      E  FATAL EXCEPTION: OkHttp TaskRunner
                                                                                                    Process: com.xxx, PID: 12596
                                                                                                    java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 1960320 free bytes and 1914KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
                                                                                                    	at okio.Segment.<init>(Segment.kt:62)
                                                                                                    	at okio.SegmentPool.take(SegmentPool.kt:90)
                                                                                                    	at okio.Buffer.writableSegment$okio(Buffer.kt:1485)
                                                                                                    	at okio.Buffer.writeByte(Buffer.kt:1315)
                                                                                                    	at okio.Buffer.writeByte(Buffer.kt:76)
                                                                                                    	at okhttp3.internal.http2.Huffman.decode(Huffman.kt:136)
                                                                                                    	at okhttp3.internal.http2.Hpack$Reader.readByteString(Hpack.kt:374)
                                                                                                    	at okhttp3.internal.http2.Hpack$Reader.readLiteralHeaderWithIncrementalIndexingIndexedName(Hpack.kt:271)
                                                                                                    	at okhttp3.internal.http2.Hpack$Reader.readHeaders(Hpack.kt:212)
                                                                                                    	at okhttp3.internal.http2.Http2Reader.readHeaderBlock(Http2Reader.kt:162)
                                                                                                    	at okhttp3.internal.http2.Http2Reader.readHeaders(Http2Reader.kt:147)
                                                                                                    	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:120)
                                                                                                    	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
                                                                                                    	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
                                                                                                    	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
                                                                                                    	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
                                                                                                    	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
                                                                                                    	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)`

The root cause seems to be the clarity's byte[] memory footprint.

**Comment by ibradwan** [comment]
Hey @Allen-ZXJ,

Yes we are aware of this issue and we've a fix for it in the testing process right now. Please stay tuned for an update on this issue.

**Comment by karthickvijayamuthu** [comment]
Hi @ibradwan leaving a message here trying to follow up on the fix for this issue. It would be amazing if we had the latest version available for us to consume & check. Please let us know

**Comment by SaadeldinBadr** [comment]
Hello everyone,
We've just released Clarity `3.2.0`, which should resolve the out-of-memory issues you've been experiencing. Please upgrade to the latest version and let us know if it resolves the problem.

**Comment by thisisadarshjaiswal** [comment]
This is still relevant. Using "@microsoft/react-native-clarity": "^4.3.2", resolving to `4.5.1`

@SaadeldinBadr @ibradwan 

<img width="670" height="391" alt="Image" src="https://github.com/user-attachments/assets/7c7ad88c-fcf9-4b53-94dc-a7032aaa0fd8" />

**Comment by ibradwan** [comment]
@thisisadarshjaiswal  @ko-devHong Thanks for sharing your concerns. Could you please share a heap dump of your apps over clarity-apps-support@microsoft.com? We need to do further investigations to see if Clarity is the source of that or not.

**Comment by deputat007** [comment]
@ibradwan 3.7.0
<img width="1058" height="405" alt="Image" src="https://github.com/user-attachments/assets/1598963a-c9de-4ce3-a761-177c31206e31" />
